# SPDX-License-Identifier: Apache-2.0
# Copyright 2023-2024 The Foundry Visionmongers Ltd

# Composite action for reuse within other workflows.
# Builds OpenAssetIO.
# Should be run on a ghcr.io/openassetio/openassetio-build container.

name: Build OpenAssetIO
description: Builds OpenAssetIO and publishes an artifact
inputs:
  install-prefix:
    description: Where to install OpenAssetIO once built
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout OpenAssetIO
      uses: actions/checkout@v3
      with:
        repository: OpenAssetIO/OpenAssetIO
        path: openassetio-checkout
        ref: v1.0.0-rc.1.0

    - name: Build OpenAssetIO
      shell: bash
      run: |
        cmake -G Ninja -S openassetio-checkout -B openassetio-checkout/build 
        cmake --build openassetio-checkout/build
        cmake --install openassetio-checkout/build --prefix ${{ inputs.install-prefix }}
